{
	"origin": [ "Where in the world am I? #Place#?  I should be in prison. ", "#greeting#, remember to thank #Place# for their sacrifice of hosting Trump today!  Someone save me.", "I escaped to #Place# but Trumps on my tail!  I need help!", "Things I  overhear: collusion....Idoit....#Phrase#......", "I'm having a great time in #Place#!  I flew away and hope to never see him again, wait, is that...?  Oh no.",  "#greeting#! Decided to stop by at #Place#!  If you live here, please keep an eye out so you don't become another victim of Trump!  Stay safe!", "Oh my, I just saw a #animal# in #Place#! I hope it carries me away somewhere safe!", "Yay!  #animal# is running off with me in #Place#!  I'm free!", "True Trump quotes: #true# #impeach", "Many words have been thrown my way like: #noun#.  And you know what?  I'm not even mad, its true.", "Boy, I sure love to dance with #animal#!  Damn it, Trump found me again... see you later friends!", "I know the real reason Trump doesn't own a pet...it's because he is afriad of #animal# and thinks that a dog will act the same way."],
	"animal": ["Aardvark", "Abyssinian", "Adelie Penguin", "Affenpinscher", "Afghan Hound", "African Bush Elephant", "African Civet", "African Clawed Frog", "African Forest Elephant", "African Palm Civet", "African Penguin", "African Tree Toad", "Airedale Terrier", "Akbash", "Akita", "Alaskan Malamute", "Albatross", "Aldabra Giant Tortoise", "Alligator", "American Staffordshire Terrier", "American Water Spaniel", "Angelfish", "Ant", "Anteater", "Antelope", "Arctic Fox", "Arctic Hare", "Arctic Wolf", "Armadillo", "Asian Elephant", "Asian Giant Hornet", "Asian Palm Civet", "Asiatic Black Bear", "Australian Mist", "Australian Shepherd", "Australian Terrier", "Avocet", "Axolotl", "Aye Aye", "Baboon", "Bactrian Camel", "Badger", "Balinese", "Banded Palm Civet", "Bandicoot", "Barb", "Barn Owl", "Barnacle", "Barracuda", "Basking Shark", "Basset Hound", "Bat", "Bavarian Mountain Hound", "Beagle", "Bear", "Bearded Collie", "Bearded Dragon", "Beaver", "Bedlington Terrier", "Beetle", "Bengal Tiger", "Bichon Frise", "Binturong", "Bird","Birds Of Paradise", "Birman", "Bison", "Black Bear", "Black Rhinoceros", "Black Russian Terrier", "Black Widow Spider", "Blue Whale", "Bobcat", "Bombay", "Bongo", "Bonobo", "Booby", "Bornean Orang-utan", "Borneo Elephant", "Boston Terrier", "Bottle Nosed Dolphin", "Boykin Spaniel", "Brazilian Terrier", "Brown Bear", "Budgerigar", "Buffalo", "Bull Mastiff", "Bull Shark", "Bull Terrier", "Bullfrog", "Bumble Bee", "Burmese", "Burrowing Frog", "Butterfly", "Butterfly Fish", "Caiman", "Caiman Lizard", "Cairn Terrier", "Camel", "Capybara", "Caracal", "Cassowary", "Caterpillar", "Catfish", "Cavalier King Charles Spaniel", "Centipede", "Cesky Fousek", "Chameleon", "Chamois", "Cheetah", "Chesapeake Bay Retriever", "Chicken", "Chimpanzee", "Chinchilla", "Chinook", "Chinstrap Penguin", "Chipmunk", "Chow Chow", "Cichlid", "Clouded Leopard", "Clown Fish", "Coati", "Cockroach", "Collared Peccary", "Collie", "Common Buzzard", "Common Frog", "Common Loon", "Common Toad", "Coral", "Cottontop Tamarin", "Cougar", "Cow", "Coyote", "Crab", "Crab-Eating Macaque", "Crane", "Crested Penguin", "Crocodile", "Cross River Gorilla", "Curly Coated Retriever", "Cuscus", "Cuttlefish", "Darwin's Frog", "Deer", "Desert Tortoise", "Deutsche Bracke", "Dhole", "Dingo", "Discus", "Doberman Pinscher", "Dodo", "Dogo Argentino", "Dogue De Bordeaux", "Dolphin",
"Donkey",
"Dormouse",
"Dragonfly",
"Drever",
"Duck",
"Dugong",
"Dunker",
"Dusky Dolphin",
"Dwarf Crocodile",
"Eagle",
"Earwig",
"Eastern Gorilla",
"Eastern Lowland Gorilla",
"Echidna",
"Edible Frog",
"Egyptian Mau",
"Electric Eel",
"Elephant",
"Elephant Seal",
"Elephant Shrew",
"Emperor Penguin",
"Emperor Tamarin",
"Emu",
"Epagneul Pont Audemer",
"Falcon",
"Fennec Fox",
"Ferret",
"Fin Whale",
"Finnish Spitz",
"Fire-Bellied Toad",
"Fish",
"Flamingo",
"Flounder",
"Fly",
"Flying Squirrel",
"Fossa",
"Fox",
"Frigatebird",
"Frilled Lizard",
"Frog",
"Fur Seal",
"Galapagos Penguin",
"Galapagos Tortoise",
"Gar",
"Gecko",
"Gentoo Penguin",
"Geoffroys Tamarin",
"Gerbil",
"Gharial",
"Giant African Land Snail",
"Giant Clam",
"Giant Panda Bear",
"Giant Schnauzer",
"Gibbon",
"Gila Monster",
"Giraffe",
"Glass Lizard",
"Glow Worm",
"Goat",
"Golden Lion Tamarin",
"Golden Oriole",
"Goose",
"Gopher",
"Gorilla",
"Grasshopper",
"Great White Shark",
"Green Bee-Eater",
"Grey Mouse Lemur",
"Grey Reef Shark",
"Grey Seal",
"Grizzly Bear",
"Grouse",
"Guinea Fowl",
"Guinea Pig",
"Guppy",
"Hammerhead Shark",
"Hamster",
"Hare",
"Harrier",
"Havanese",
"Hedgehog",
"Hercules Beetle",
"Hermit Crab",
"Heron",
"Highland Cattle",
"Himalayan",
"Hippopotamus",
"Honey Bee",
"Horn Shark",
"Horned Frog",
"Horse",
"Horseshoe Crab",
"Howler Monkey",
"Human",
"Humboldt Penguin",
"Hummingbird",
"Humpback Whale",
"Hyena",
"Ibis",
"Ibizan Hound",
"Iguana",
"Impala",
"Indian Elephant",
"Indian Palm Squirrel",
"Indian Rhinoceros",
"Indian Star Tortoise",
"Indochinese Tiger",
"Indri",
"Insect",
"Jackal",
"Jaguar",
"Japanese Chin",
"Japanese Macaque",
"Javan Rhinoceros",
"Javanese",
"Jellyfish",
"Kakapo",
"Kangaroo",
"Keel Billed Toucan",
"Killer Whale",
"King Crab",
"King Penguin",
"Kingfisher",
"Kiwi",
"Koala",
"Komodo Dragon",
"Kudu",
"Labradoodle",
"Labrador Retriever",
"Ladybird",
"Leaf-Tailed Gecko",
"Lemming",
"Lemur",
"Leopard",
"Leopard Cat",
"Leopard Seal",
"Leopard Tortoise",
"Liger",
"Lion",
"Lionfish",
"Little Penguin",
"Lizard",
"Llama",
"Lobster",
"Long-Eared Owl",
"Lynx",
"Macaroni Penguin",
"Macaw",
"Magellanic Penguin",
"Magpie",
"Malayan Civet",
"Malayan Tiger",
"Manatee",
"Mandrill",
"Manta Ray",
"Marine Toad",
"Markhor",
"Marsh Frog",
"Masked Palm Civet",
"Mayfly",
"Meerkat",
"Millipede",
"Minke Whale",
"Mole",
"Molly",
"Mongoose",
"Mongrel",
"Monitor Lizard",
"Monkey",
"Monte Iberia Eleuth",
"Moorhen",
"Moose",
"Moray Eel",
"Moth",
"Mountain Gorilla",
"Mountain Lion",
"Mouse",
"Mule",
"Neanderthal",
"Neapolitan Mastiff",
"Newfoundland",
"Newt",
"Nightingale",
"Norwegian Forest",
"Numbat",
"Nurse Shark",
"Ocelot",
"Octopus",
"Okapi",
"Olm",
"Opossum",
"Orang-utan",
"Ostrich",
"Otter",
"Oyster",
"Pademelon",
"Panther",
"Parrot",
"Patas Monkey",
"Peacock",
"Pelican",
"Penguin",
"Persian",
"Pheasant",
"Pied Tamarin",
"Pig",
"Pika",
"Pike",
"Pink Fairy Armadillo",
"Piranha",
"Platypus",
"Pointer",
"Poison Dart Frog",
"Polar Bear",
"Pond Skater",
"Pool Frog",
"Porcupine",
"Possum",
"Prawn",
"Proboscis Monkey",
"Puffer Fish",
"Puffin",
"Pug",
"Puma",
"Purple Emperor",
"Puss Moth",
"Pygmy Hippopotamus",
"Pygmy Marmoset",
"Quail",
"Quetzal",
"Quokka",
"Quoll",
"Rabbit",
"Raccoon",
"Radiated Tortoise",
"Ragdoll",
"Rat",
"Rattlesnake",
"Red Knee Tarantula",
"Red Panda",
"Red Wolf",
"Red-handed Tamarin",
"Reindeer",
"Rhinoceros",
"River Dolphin",
"River Turtle",
"Robin",
"Rock Hyrax",
"Rockhopper Penguin",
"Roseate Spoonbill",
"Royal Penguin",
"Russian Blue",
"Sabre-Toothed Tiger",
"Saint Bernard",
"Salamander",
"Sand Lizard",
"Saola",
"Scorpion",
"Scorpion Fish",
"Sea Dragon",
"Sea Lion",
"Sea Otter",
"Sea Slug",
"Sea Squirt",
"Sea Turtle",
"Sea Urchin",
"Seahorse",
"Seal",
"Serval",
"Sheep",
"Shih Tzu",
"Shrimp",
"Siamese Fighting Fish",
"Siberian Tiger",
"Silver Dollar",
"Skunk",
"Sloth",
"Slow Worm",
"Snail",
"Snake",
"Snapping Turtle",
"Snowshoe",
"Snowy Owl",
"Somali",
"South China Tiger",
"Spadefoot Toad",
"Sparrow",
"Spectacled Bear",
"Sperm Whale",
"Spider Monkey",
"Spiny Dogfish",
"Sponge",
"Squid",
"Squirrel",
"Squirrel Monkey",
"Sri Lankan Elephant",
"Stag Beetle",
"Starfish",
"Stellers Sea Cow",
"Stick Insect",
"Stingray",
"Stoat",
"Striped Rocket Frog",
"Sumatran Elephant",
"Sumatran Orang-utan",
"Sumatran Rhinoceros",
"Sumatran Tiger",
"Sun Bear",
"Swan",
"Tang",
"Tapanuli Orang-utan",
"Tapir",
"Tarsier",
"Tasmanian Devil",
"Tawny Owl",
"Termite",
"Tetra",
"Thorny Devil",
"Tibetan Mastiff",
"Tiffany",
"Tiger",
"Tiger Salamander",
"Tiger Shark",
"Tortoise",
"Toucan",
"Tree Frog",
"Tropicbird",
"Tuatara",
"Turkey",
"Turkish Angora",
"Uakari",
"Uguisu",
"Umbrellabird",
"Vampire Bat",
"Vervet Monkey",
"Vulture",
"Wallaby",
"Walrus",
"Warthog",
"Wasp",
"Water Buffalo",
"Water Dragon",
"Water Vole",
"Weasel",
"Welsh Corgi",
"West Highland Terrier",
"Western Gorilla",
"Western Lowland Gorilla",
"Whale Shark",
"Whippet",
"White Faced Capuchin",
"White Rhinoceros",
"White Tiger",
"Wild Boar",
"Wildebeest",
"Wolf",
"Wolverine",
"Wombat",
"Woodlouse",
"Woodpecker",
"Woolly Mammoth",
"Woolly Monkey",
"Wrasse",
"X-Ray Tetra",
"Yak",
"Yellow-Eyed Penguin",
"Yorkshire Terrier",
"Zebra",
"Zebra Shark",
"Zebu",
"Zonkey",
"Zorse"],
	"noun": ["pheasant", "bug", "far too expensive bunch of thread", "taxpayer payed bunch of twigs", "bobcat toy", "meat hat",  "ass hat", "corn colored corncob", "little son", "politician hat made by mommy", "Last minute cosplay", "leftover mop", "water", "vegan top hat", "purple pestilence", "pelicans dinner", "day old fish", "cat vomit", "college student funded wig", "MAGA hat extension", "disrespecting women wig"],
	"adjective": ["horrendous", "vegan", "scrawny", "questionable", "swift", "(you said hair Jimmy?  That doesn't sound quite right.)", "quality", "affordable", "menswear", "unfitting", "gross", "updo"],
	"greeting": ["Howdy", "What's up ya'll", "Yo", "Welcome", "It's me again"],
	"Phrase": ["Putin is huuuuge, the best", "I hate everyone", "Alright! I did it!  Okay?  I did the bad stuff." , "mexicans are in Spain and it's all crazy."],
	"true": ["I've always said, 'If you need Viagra, you're probably with the wrong girl.'", "I love her … upper body.", "Look at that face. Would anybody vote for that? Can you imagine that, the face of our next president? I mean, she's a woman, and I'm not supposed to say bad things, but really, folks, come on. Are we serious?", "Why does she keep interrupting everybody?", "She's certainly not hot.", "Horseface" , "I promise not to talk about your massive plastic surgeries that didn't work.",  "I know where she went, it's disgusting, I don't want to talk about it … No, it's too disgusting. Don't say it, it's disgusting.", "If she were a man, I don't think she'd get five percent of the vote." , "Does she look presidential, fellas? Give me a break.", "Such a nasty woman.", "Unattractive both inside and out. I fully understand why her former husband left her for a man — he made a good decision.", "A crazed, crying lowlife", "Does she have a good body? No. Does she have a fat ass? Absolutely.", "Sadly, she's no longer a 10.", "She does have a very nice figure ... if [she] weren't my daughter, perhaps I'd be dating her.",  "She's actually always been very voluptuous.","How do the breasts look?", "Well, I think that she's got a lot of Marla. She's a really beautiful baby, and she's got Marla's legs. We don't know whether she's got this part yet, but time will tell.", "26,000 unreported sexual assaults in the military — only 238 convictions. What did these geniuses expect when they put men & women together?", "We could say, politically correct, that look doesn't matter, but the look obviously matters. Like you wouldn't have your job if you weren't beautiful.", "I've got to use some Tic Tacs, just in case I start kissing her. You know I'm automatically attracted to beautiful — I just start kissing them. It's like a magnet. Just kiss. I don't even wait. And when you're a star, they let you do it. You can do anything ... Grab them by the pussy. You can do anything." , "Nobody has more respect for women than I do. Nobody. Nobody has more respect." ],
	"Place": ["Afghanistan", "Albania", "Algeria", "Andorra",  "Angola",  "Antigua and Barbuda",  "Argentina",  "Armenia",  "Australia",  "Austria", "Azerbaijan", "The Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "the Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "the Democratic Republic of the Congo", "Costa Rica", "Côte d’Ivoire", "Croatia", "Cuba","Cyprus","the Czech Republic","Denmark","Djibouti","Dominica","Dominican Republic","East Timor (Timor-Leste)","Ecuador","Egypt","El Salvador","Equatorial Guinea","Eritrea","Estonia","Eswatini","Ethiopia","Fiji","Finland","France","Gabon","The Gambia","Georgia","Germany","Ghana","Greece","Grenada","Guatemala","Guinea","Guinea-Bissau","Guyana","Haiti","Honduras","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel","Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kiribati","Korea, North","Korea, South","Kosovo","Kuwait","Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","the Marshall Islands","Mauritania","Mauritius","Mexico","Micronesia","Moldova","Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar (Burma)","Namibia","Nauru","Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria","North Macedonia","Norway","Oman","Pakistan","Palau","Panama","Papua New Guinea","Paraguay","Peru","the Philippines","Poland","Portugal","Qatar","Romania","Russia","Rwanda","Saint Kitts and Nevis","Saint Lucia","Saint Vincent and the Grenadines","Samoa","San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","the Solomon Islands","Somalia","South Africa","Spain","Sri Lanka","Sudan","Sudan, South","Suriname","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Togo","Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Tuvalu","Uganda","Ukraine","the United Arab Emirates","the United Kingdom","the United States","Uruguay","Uzbekistan","Vanuatu","Vatican City","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe"]

}



